### ISSUE TITLE
Login form for user & admin

### ISSUE THREAD

**Issue by raoasifraza11** [fsdevelopers/ani-motors#6]
Need a login for for user and admin both.

**Comment by raoasifraza11** [comment]
@Ahmadkhan12345566 @hariskhurshid

**Comment by raoasifraza11** [comment]
Done in #17

**Comment by Ahmadkhan12345566** [comment]
kindly close this issue

**Comment by raoasifraza11** [comment]
👍 🥇 hehehehe

**Comment by raoasifraza11** [comment]
![screen shot 2017-10-12 at 11 02 59 pm](https://user-images.githubusercontent.com/18229291/31511554-8b975ca0-afa1-11e7-8ec7-7b191f4e93f2.png)
Look at this image
